
import type { Category } from './types';

export const AI_TOOLS_CATEGORIES: Category[] = [
  {
    title: "Writing & Content Creation",
    tools: [
      { name: "ChatGPT (OpenAI)", purpose: "General-purpose writing, coding, brainstorming", link: "https://chat.openai.com", pricing: "Freemium" },
      { name: "Claude (Anthropic)", purpose: "Long-form, research-heavy writing", link: "https://claude.ai", pricing: "Freemium" },
      { name: "Writesonic", purpose: "Blog posts, ads, SEO content", link: "https://writesonic.com", pricing: "Paid" },
      { name: "Copy.ai", purpose: "Marketing & ad copy", link: "https://copy.ai", pricing: "Paid" },
      { name: "Jasper", purpose: "Automated marketing content", link: "https://jasper.ai", pricing: "Paid" },
      { name: "Sudowrite", purpose: "Creative story writing", link: "https://sudowrite.com", pricing: "Paid" },
      { name: "Anyword", purpose: "AI ad copy optimizer", link: "https://anyword.com", pricing: "Paid" },
      { name: "Rytr", purpose: "Quick short-form writing", link: "https://rytr.me", pricing: "Freemium" },
      { name: "Quillbot", purpose: "Paraphrasing & grammar", link: "https://quillbot.com", pricing: "Freemium" },
      { name: "Grammarly", purpose: "Grammar & style checks", link: "https://grammarly.com", pricing: "Freemium" },
    ],
  },
  {
    title: "Image Generation & Editing",
    tools: [
      { name: "DALL·E 3", purpose: "AI image generation", link: "https://openai.com/dall-e", pricing: "Freemium" },
      { name: "Midjourney", purpose: "Artistic & realistic visuals", link: "https://midjourney.com", pricing: "Freemium" },
      { name: "Stable Diffusion", purpose: "Open-source image AI", link: "https://stability.ai", pricing: "Freemium" },
      { name: "Leonardo.ai", purpose: "Game asset creation", link: "https://leonardo.ai", pricing: "Freemium" },
      { name: "Runway ML", purpose: "Image/video editing", link: "https://runwayml.com", pricing: "Freemium" },
      { name: "Fotor AI", purpose: "AI photo editing", link: "https://fotor.com", pricing: "Freemium" },
      { name: "Canva AI", purpose: "Design & templates", link: "https://canva.com", pricing: "Freemium" },
      { name: "Adobe Firefly", purpose: "AI creative suite", link: "https://adobe.com/firefly", pricing: "Freemium" },
      { name: "Clipdrop", purpose: "AI background removal", link: "https://clipdrop.co", pricing: "Freemium" },
      { name: "Remini", purpose: "Photo enhancement", link: "https://remini.ai", pricing: "Freemium" },
    ],
  },
    {
    title: "Study & Research",
    tools: [
        { name: "Perplexity AI", purpose: "AI search with citations", link: "https://perplexity.ai", pricing: "Free" },
        { name: "Elicit", purpose: "Research automation", link: "https://elicit.org", pricing: "Freemium" },
        { name: "Scholarcy", purpose: "Paper summaries", link: "https://scholarcy.com", pricing: "Freemium" },
        { name: "SciSpace", purpose: "Research & citations", link: "https://scispace.com", pricing: "Freemium" },
        { name: "ChatPDF", purpose: "Talk to PDFs", link: "https://chatpdf.com", pricing: "Free" },
        { name: "Paperpile", purpose: "Reference manager", link: "https://paperpile.com", pricing: "Paid" },
        { name: "Connected Papers", purpose: "Research map", link: "https://connectedpapers.com", pricing: "Free" },
        { name: "Consensus", purpose: "Find research consensus", link: "https://consensus.app", pricing: "Paid" },
        { name: "Wolfram Alpha", purpose: "Computational knowledge", link: "https://wolframalpha.com", pricing: "Paid" },
        { name: "Google Bard", purpose: "Research & Q&A", link: "https://bard.google.com", pricing: "Free" },
    ],
  },
    {
    title: "Coding & Development",
    tools: [
        { name: "GitHub Copilot", purpose: "AI code assistant", link: "https://github.com/copilot", pricing: "Freemium" },
        { name: "Replit Ghostwriter", purpose: "AI coding", link: "https://replit.com", pricing: "Freemium" },
        { name: "Codeium", purpose: "Free AI coding tool", link: "https://codeium.com", pricing: "Freemium" },
        { name: "Tabnine", purpose: "Code autocompletion", link: "https://tabnine.com", pricing: "Paid" },
        { name: "AskCodi", purpose: "Dev AI assistant", link: "https://askcodi.com", pricing: "Paid" },
        { name: "Warp AI", purpose: "Smart terminal", link: "https://warp.dev", pricing: "Paid" },
        { name: "Mutable.ai", purpose: "AI code generation", link: "https://mutable.ai", pricing: "Paid" },
        { name: "Codium AI", purpose: "Code testing help", link: "https://codium.ai", pricing: "Paid" },
        { name: "Blackbox AI", purpose: "Search code snippets", link: "https://blackbox.ai", pricing: "Paid" },
        { name: "Sourcery", purpose: "Auto-refactor code", link: "https://sourcery.ai", pricing: "Paid" },
    ],
  },
  {
    title: "Video Creation & Editing",
    tools: [
      { name: "Pika Labs", purpose: "Text-to-video", link: "https://pika.art", pricing: "Freemium" },
      { name: "Runway Gen-2", purpose: "AI video generation", link: "https://runwayml.com", pricing: "Freemium" },
      { name: "Synthesia", purpose: "AI avatars for videos", link: "https://synthesia.io", pricing: "Paid" },
      { name: "Descript", purpose: "Edit video with text", link: "https://descript.com", pricing: "Freemium" },
      { name: "Fliki", purpose: "AI voice & video creation", link: "https://fliki.ai", pricing: "Freemium" },
      { name: "Kapwing AI", purpose: "Quick video edits", link: "https://kapwing.com", pricing: "Freemium" },
      { name: "HeyGen", purpose: "AI presenter videos", link: "https://heygen.com", pricing: "Freemium" },
      { name: "Veed.io", purpose: "Online video editing", link: "https://veed.io", pricing: "Freemium" },
      { name: "DeepBrain AI", purpose: "Realistic AI humans", link: "https://deepbrain.io", pricing: "Paid" },
      { name: "InVideo", purpose: "Social media video creation", link: "https://invideo.io", pricing: "Freemium" },
    ],
  },
  {
    title: "Audio & Music",
    tools: [
        { name: "ElevenLabs", purpose: "Ultra-realistic AI voices", link: "https://elevenlabs.io", pricing: "Freemium" },
        { name: "Voicemod", purpose: "Live voice changer", link: "https://voicemod.net", pricing: "Freemium" },
        { name: "AIVA", purpose: "AI music composer", link: "https://aiva.ai", pricing: "Paid" },
        { name: "Soundraw", purpose: "Music generation", link: "https://soundraw.io", pricing: "Paid" },
        { name: "LALAL.AI", purpose: "Voice/instrument separation", link: "https://lalal.ai", pricing: "Freemium" },
        { name: "Mubert", purpose: "AI background music", link: "https://mubert.com", pricing: "Freemium" },
        { name: "Murf AI", purpose: "AI voiceovers", link: "https://murf.ai", pricing: "Paid" },
        { name: "Beatoven.ai", purpose: "Mood-based music creation", link: "https://beatoven.ai", pricing: "Paid" },
        { name: "Boomy", purpose: "Make music instantly", link: "https://boomy.com", pricing: "Freemium" },
        { name: "Voicify", purpose: "Create celebrity voices", link: "https://voicify.ai", pricing: "Paid" },
    ],
  },
  {
    title: "Business & Productivity",
    tools: [
        { name: "Notion AI", purpose: "Smart notes & docs", link: "https://notion.so", pricing: "Freemium" },
        { name: "Tome", purpose: "AI presentation builder", link: "https://tome.app", pricing: "Freemium" },
        { name: "ClickUp AI", purpose: "Task management", link: "https://clickup.com", pricing: "Freemium" },
        { name: "Gamma", purpose: "AI slides & docs", link: "https://gamma.app", pricing: "Freemium" },
        { name: "Fireflies.ai", purpose: "Meeting transcription", link: "https://fireflies.ai", pricing: "Freemium" },
        { name: "Motion", purpose: "AI scheduling", link: "https://usemotion.com", pricing: "Paid" },
        { name: "Superhuman AI", purpose: "AI-powered email", link: "https://superhuman.com", pricing: "Paid" },
        { name: "Mem.ai", purpose: "AI knowledge base", link: "https://mem.ai", pricing: "Paid" },
        { name: "Taskade AI", purpose: "Productivity workspace", link: "https://taskade.com", pricing: "Paid" },
        { name: "Magical AI", purpose: "Automation assistant", link: "https://magical.so", pricing: "Paid" },
    ],
  },
  {
    title: "Design & UI/UX",
    tools: [
        { name: "Uizard", purpose: "Turn sketches to UI", link: "https://uizard.io", pricing: "Freemium" },
        { name: "Figma AI", purpose: "Design with AI", link: "https://figma.com", pricing: "Freemium" },
        { name: "Khroma", purpose: "AI color palettes", link: "https://khroma.co", pricing: "Free" },
        { name: "Galileo AI", purpose: "Generate app UI", link: "https://galileo.ai", pricing: "Paid" },
        { name: "Colormind", purpose: "Color scheme generator", link: "https://colormind.io", pricing: "Free" },
        { name: "Designs.ai", purpose: "All-in-one design", link: "https://designs.ai", pricing: "Paid" },
        { name: "Vizcom", purpose: "AI concept art", link: "https://vizcom.co", pricing: "Freemium" },
        { name: "Brandmark", purpose: "Logo creation", link: "https://brandmark.io", pricing: "Paid" },
        { name: "Looka", purpose: "AI brand design", link: "https://looka.com", pricing: "Paid" },
        { name: "Logomaster AI", purpose: "Logo generator", link: "https://logomaster.ai", pricing: "Paid" },
    ],
  },
  {
    title: "Fun & Entertainment",
    tools: [
        { name: "Character.AI", purpose: "Talk to characters", link: "https://character.ai", pricing: "Freemium" },
        { name: "NovelAI", purpose: "Story & roleplay", link: "https://novelai.net", pricing: "Freemium" },
        { name: "ChatFAI", purpose: "Celebrity chat", link: "https://chatfai.com", pricing: "Freemium" },
        { name: "Scenario", purpose: "Game assets", link: "https://scenario.com", pricing: "Freemium" },
        { name: "This Person Does Not Exist", purpose: "AI faces", link: "https://thispersondoesnotexist.com", pricing: "Free" },
        { name: "Deep Nostalgia", purpose: "Animate photos", link: "https://myheritage.com", pricing: "Paid" },
        { name: "Wombo Dream", purpose: "AI art generator", link: "https://app.wombo.art", pricing: "Free" },
        { name: "Reface", purpose: "Face swap videos", link: "https://reface.ai", pricing: "Paid" },
        { name: "AI Dungeon", purpose: "Interactive stories", link: "https://aidungeon.io", pricing: "Freemium" },
        { name: "MemeCam", purpose: "AI meme maker", link: "https://memecam.com", pricing: "Free" },
    ],
  },
  {
    title: "Personal Assistant & Daily Use",
    tools: [
        { name: "Pi", purpose: "Friendly personal AI", link: "https://heypi.com", pricing: "Freemium" },
        { name: "Heyday", purpose: "Memory assistant", link: "https://heyday.xyz", pricing: "Paid" },
        { name: "Otter.ai", purpose: "Transcribe meetings", link: "https://otter.ai", pricing: "Freemium" },
        { name: "Speechify", purpose: "Text-to-speech", link: "https://speechify.com", pricing: "Freemium" },
        { name: "Monica", purpose: "Personal AI assistant", link: "https://monica.im", pricing: "Paid" },
        { name: "Rewind AI", purpose: "Record everything on PC", link: "https://rewind.ai", pricing: "Paid" },
        { name: "Sembly AI", purpose: "Meeting summaries", link: "https://sembly.ai", pricing: "Paid" },
        { name: "Genie AI", purpose: "WhatsApp chatbot", link: "https://genieai.chat", pricing: "Paid" },
        { name: "Your AI Butler", purpose: "Life organizer", link: "https://youraibutler.com", pricing: "Paid" },
        { name: "Personal.ai", purpose: "AI memory keeper", link: "https://personal.ai", pricing: "Paid" },
    ],
  }
];
